name: Build and Extract Clients

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "port-api-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: localhost:5000/port-api:latest

      - name: Run container and copy clients
        run: |
          docker run --name port-api-container localhost:5000/port-api:latest
          docker cp port-api-container:/app/clients clients
          docker rm port-api-container

      - name: Commit and push clients
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-commit generated clients"
          branch: ${{ github.ref }}
          file_pattern: clients/**
