name: Build and Extract Clients

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "port-api-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  generate_clients:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [javascript, typescript, python, java, go, bash, r, ruby, php, rust]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Port Docs repo
        run: |
         git clone https://github.com/port-labs/port-docs.git
         cp port-docs/static/spectmp.yaml openapi.yaml
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: 'latest'

      - name: Set up Java
        if: matrix.language == 'java'
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 'latest'

      - name: Set up R
        if: matrix.language == 'r'
        uses: r-lib/actions/setup-r@v2

      - name: Set up Ruby
        if: matrix.language == 'ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'latest'

      - name: Set up PHP
        if: matrix.language == 'php'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'

      - name: Set up Rust
        if: matrix.language == 'rust'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set up Node.js for TypeScript
        if: matrix.language == 'typescript'
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Set up Node.js for JavaScript
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Set up Go
        if: matrix.language == 'go'
        uses: actions/setup-go@v4
        with:
          go-version: 'latest'

      - name: Set up Bash
        if: matrix.language == 'bash'
        run: echo "Bash does not require a specific setup action"

      - name: Install openapi-generator-cli
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Generate clients for ${{ matrix.language }}
        run: |
          mkdir -p clients/${{ matrix.language }}
          openapi-generator-cli generate -i openapi.yaml -g ${{ matrix.language }} -o clients/${{ matrix.language }}

      - name: Save clients
        uses: actions/upload-artifact@v3
        with:
          name: clients-${{ matrix.language }}
          path: clients/${{ matrix.language }}

  commit_clients:
    runs-on: ubuntu-latest
    needs: generate_clients
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download clients
        uses: actions/download-artifact@v3
        with:
          name: clients-${{ matrix.language }}
          path: ./clients/${{ matrix.language }}

      - name: Commit and push clients
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-commit generated clients for ${{ matrix.language }}"
          branch: ${{ github.ref }}
          file_pattern: clients/**
