name: Build and Extract Clients

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "port-api-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run container and copy clients
        run: make run
      - name: Commit and push clients
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-commit generated clients"
          branch: ${{ github.ref }}
          file_pattern: clients/**
